api_platform:
  title: Aln-Symfony
  description: 'More infos on Github: https://github.com/Dean151/Aln-Symfony'
  version: 0.3.0
  show_webby: false
  formats:
    json: [ 'application/json' ]
    jsonld: ['application/ld+json']
  defaults:
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
    normalization_context:
      skip_null_values: false
  use_symfony_listeners: true
  swagger:
    api_keys:
      JWT:
        name: 'Authorization'
        type: 'header'
