#!/usr/bin/env bash

set -e

./bin/console -e prod doctrine:database:create --no-interaction --if-not-exists
./bin/console -e prod doctrine:migration:migrate --no-interaction --all-or-nothing --allow-no-migration

# TODO: Restart Socket!
